branch-defaults:
  node_server:
    environment: Antelope-dev
global:
  application_name: Antelope
  default_ec2_keyname: antelope-eb
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
